name: CI tests
on:
  pull_request:

  push:
    branches:
      - main

env:
  FORCE_COLOR: true

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Run linters and other pre-commit hooks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.x"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Run pre-commit
        run: |
          uv run pre-commit run --all-files --show-diff-on-failure

  pytest:
    name: Run Python unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # tests need an unshallowed version of the repository to check the version
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.x"
          enable-cache: true

      - name: Install locked versions of dependencies
        run: |
          uv sync --all-extras

      - name: Run all tests
        run: |
          uv run pytest -rs -vvv
